function PLUGIN:EnvKeys(ctx)
	local project_root = os.getenv("MISE_PROJECT_ROOT") or os.getenv("PWD")
	local pyproject = project_root .. "/pyproject.toml"
	local uv_lock = project_root .. "/uv.lock"
	local poetry_lock = project_root .. "/poetry.lock"

	-- Stop if no pyproject.toml is detected
	local f = io.open(pyproject, "r")
	if not f then
		return {}
	end
	f:close()

	-- Stop if uv is handling this project instead
	local uv_f = io.open(uv_lock, "r")
	if uv_f then
		uv_f:close()
		return {}
	end

	-- MISE_POETRY_VENV_AUTO check
	local venv_auto = os.getenv("MISE_POETRY_VENV_AUTO")
	if venv_auto == "1" or venv_auto == "true" then
		local lock_f = io.open(poetry_lock, "r")
		if not lock_f then
			return {}
		end
		lock_f:close()
	end

	-- Safely get the installation root path for Poetry
	local install_root = ctx.runtimePath or ctx.installPath or ctx.rootPath
	if not install_root then
		return {}
	end
	local poetry_bin = install_root .. "/bin/poetry"

	-- -----------------------------------------------------------------
	-- THE FIX: Locate the active mise python executable inside the sandbox
	-- -----------------------------------------------------------------
	local python_bin = "python3" -- fallback
	local home = os.getenv("HOME")

	-- Parse the local .mise.toml to see what python version is requested
	local mise_toml_path = project_root .. "/.mise.toml"
	local mt = io.open(mise_toml_path, "r")
	if mt then
		local content = mt:read("*a")
		mt:close()
		-- Extract the pinned python version number via regex
		local py_ver = content:match('python%s*=%s*"([%d%.]+)"')
		if py_ver then
			local suspected_path = home .. "/.local/share/mise/installs/python/" .. py_ver .. "/bin/python3"
			local check_f = io.open(suspected_path, "r")
			if check_f then
				check_f:close()
				python_bin = suspected_path
			end
		end
	end

	-- 1. Force Poetry to use the specific Python binary requested by the project
	os.execute(string.format("%s --directory %s env use %s >/dev/null 2>&1", poetry_bin, project_root, python_bin))

	-- 2. Query the exact path generated by Poetry's virtualenv manager
	local handle = io.popen(string.format("%s --directory %s env info --path 2>/dev/null", poetry_bin, project_root))
	local venv_path = handle:read("*a")
	handle:close()

	if venv_path and venv_path ~= "" then
		venv_path = venv_path:gsub("%s+$", "") -- Clean trailing whitespace
		local venv_bin = venv_path .. "/bin"

		-- 3. Run automated dependency sync if requested
		local auto_install = os.getenv("MISE_POETRY_AUTO_INSTALL")
		if auto_install == "1" or auto_install == "true" then
			print("mise-poetry: Synchronizing packages via Poetry installer...")
			os.execute(string.format("%s --directory %s install", poetry_bin, project_root))
		end

		-- 4. Overwrite PATH variable completely inside the returned table.
		-- This forces mise to place our .venv binaries ahead of the tool shims.
		return {
			{ key = "VIRTUAL_ENV", value = venv_path },
			{ key = "POETRY_ACTIVE", value = "1" },
			{ key = "PATH", value = venv_bin .. ctx.pathSeparator .. os.getenv("PATH") },
		}
	end

	return {}
end
